name: Monthly Dashboard Update
on:
  schedule:
    - cron: '0 0 1 * *'  # Runs at midnight on the 1st of every month

jobs:
  update-dashboard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run data cleaning notebook (Final Project.ipynb)
        run: |
          pip install nbconvert  # Ensure Jupyter is installed
          jupyter nbconvert --execute --to notebook --inplace "Final Project.ipynb"

      - name: Commit & Push updated data
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add cleaned_data.xlsx
          git commit -m "Monthly data update"
          git push

      - name: Run Streamlit dashboard
        run: streamlit run dashboard.py
